//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf401
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品
    {
        public int 商品ID { get; set; }
        public string 商品名 { get; set; }
        public int 単価 { get; set; }
    }
}
